[versions]
core-ktx = "1.10.1"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.8.1"
androidx-appcompat-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"